# Generated by Django 3.0.6 on 2021-01-17 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_filters', '0003_auto_20180610_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedfilter',
            name='delete',
            field=models.BooleanField(null=False, default=False),
        ),
    ]
