# Generated by Django 3.0.6 on 2021-01-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_filters', '0004_auto_20210117_1260'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedfilter',
            name='b64_fake_query',
            field=models.CharField(max_length=2048, null=True, blank=True),
        ),
    ]
